# Generated by Django 2.1.2 on 2019-01-11 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Published title')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('image_240x135', models.URLField(verbose_name='Image 240x135')),
                ('image_480x270', models.URLField(verbose_name='Image 480x270')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
    ]
